"""empty message

Revision ID: b821e25c0039
Revises: eed10b53eab6
Create Date: 2024-09-09 20:13:26.873620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b821e25c0039'
down_revision = 'eed10b53eab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('IdEvent', sa.Integer(), nullable=False),
    sa.Column('Event_name', sa.String(length=150), nullable=True),
    sa.Column('Event_date', sa.Date(), nullable=True),
    sa.Column('Event_time', sa.Time(), nullable=True),
    sa.Column('Event_place', sa.String(length=150), nullable=True),
    sa.Column('Event_final', sa.Integer(), nullable=True),
    sa.Column('Event_season', sa.String(length=10), nullable=True),
    sa.Column('Results_file_name', sa.String(length=100), nullable=True),
    sa.Column('Results_file_ext', sa.String(length=10), nullable=True),
    sa.Column('Results_file_url', sa.String(length=100), nullable=True),
    sa.Column('Propositions_file_name', sa.String(length=100), nullable=True),
    sa.Column('Propositions_file_ext', sa.String(length=10), nullable=True),
    sa.Column('Propositions_file_url', sa.String(length=100), nullable=True),
    sa.Column('Event_organizator', sa.String(length=100), nullable=True),
    sa.Column('Event_badge', sa.String(length=100), nullable=True),
    sa.Column('Event_opened', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IdEvent')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
